apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: manual
  capacity:
  # Kapasitas penyimpanan
    storage: 1Gi 
  accessModes:
  # Hanya bisa diakses satu pod dalam satu waktu
    - ReadWriteOnce 
  hostPath:
    # Path di host lokal untuk simpan data
    path: "/data/db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  # Gunakan PVC Manual
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     # Permintaan storage 1Gi
      storage: 1Gi

