apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  # Jumlah pod
  replicas: 1
  selector:
    matchLabels:
      # Pilih pod berdasarkan label
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      # Waktu grace sebelum shutdown
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          # Gunakan image MongoDB
          image: mongo:7.0
          ports:
            - containerPort: 27017
              name: mongo
          # Ambil username & password dari secret
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: data
              # Mount volume untuk data
              mountPath: /data/db
            - name: config
              # Mount file konfigurasi
              mountPath: /config
            - name: secret
              mountPath: /etc/mongo-credentials
      volumes:
        - name: config
          configMap:
            # Ambil dari ConfigMap
            name: mongo-config
            items:
              - key: mongo.conf
                path: mongo.conf
        - name: data
          persistentVolumeClaim:
            # Gunakan PVC
            claimName: mongo-pvc
        - name: secret
          secret:
            secretName: mongo-secret

